//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivrariaEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class livros
    {
        public int id_livro { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string sinopse { get; set; }
        public int ano { get; set; }
        public string categoria { get; set; }
        public string editora { get; set; }
        public string isbn { get; set; }
    }
}
